version: "3"

services:
  graphdb:
    image: dhlabbasel/graphdb-free
    ports:
      - 7200:7200
    depends_on:
      - salsah

  knora:
    image: nieine/knora
    ports:
      - 3333:3333
    depends_on:
      - graphdb
    volumes:
      - ./tmp/webapimp:/tmp/webapi_tmp/

  sipi:
    image: nieine/sipi
    ports:
      - 1024:1024
    volumes:
      - ./tmp:/tmp
      - $HOME:$HOME
      - ./images:/sipi/images
      - ./tmp/webapitmp:/tmp/webapi_tmp/
    extra_hosts:
     - "webapihost:10.12.248.127"

  salsah:
    image: nieine/salsah
    ports:
      - 4200:4200