 - name: "Update Kernel"
   command: yum update kernel -y

 - name: "Update"
   command: yum update -y

 - name: "Upgrade"
   command: yum upgrade

 - name: "Install git"
   yum: 
     name: git
     state: latest

 - name: "Clone Salsah"
   git: 
     repo: https://github.com/nie-ine/Salsah.git
     dest: /root/Salsah
   ignore_errors: yes

 - name: "Install needed packages for npm"
   command: yum install -y gcc-c++ make

 - name: "Get Package"
   command: curl -sL https://rpm.nodesource.com/setup_6.x

 - name: "Install npm"
   command: yum install nodejs -y

 - name: "Update npm"
   command: npm install -g npm@latest

 - name: "Install angular cli"
   command: npm install --unsafe-perm --verbose -g @angular/cli@1.0.0
 
 - name: "Install node sass"
   command: npm install --unsafe-perm node-sass

 - name: "npm install in Salsah"
   npm: 
     path: /root/Salsah
   ignore_errors: yes

 - name: "ng serve"
   shell: ng serve --host 10.65.4.10 -port 4300 &
   args:
     chdir: /root/Salsah

 - name: "Clone Knora"
   git:
     repo: https://github.com/nie-ine/Knora.git
     dest: /root/Knora
   ignore_errors: yes

 - name: "Copy and unarchive"
   unarchive:
     src: /home/ubuntu/InstallKnoraSalsahSipi.zip
     dest: /root

 - name: "Install Java jre"
   shell: yum localinstall jre-8u60-linux-x64.rpm -y
   args:
     chdir: /root/InstallKnoraSalsahSipi

 - name: "Install Java Jdk"
   shell: yum localinstall jdk-8u60-linux-x64.rpm -y
   args:
     chdir: /root/InstallKnoraSalsahSipi

 - name: "Set java jdk variable"
   shell: export JAVA_HOME=/usr/java/jdk1.8.0_60/

 - name: "Set java bin variable"
   shell: export PATH=$PATH:\$JAVA_HOME/bin

 - name: "Install sbt"
   yum:
     name: sbt
     state: latest

 - name: "SBT compile"
   shell: sbt compile
   args:
     chdir: /root/InstallKnoraSalsahSipi/Knora

 - name: "Start Fuseki Server"
   shell: echo "./fuseki-server " > executeScript.sh && chmod +x executeScript.sh && ./executeScript.sh 
   args:
     chdir: /root/Knora/triplestores/fuseki 


