version: "3"

services:
  graphdb:
    image: dhlabbasel/graphdb-free
    ports:
      - 7200:7200
    depends_on:
      - salsah

  knora:
    build: ./Knora
    ports:
      - 3333:3333
    depends_on:
      - graphdb
    volumes:
      - ./Knora/webapi/src/main:/Knora/webapi/src/main
      - ./webapiTmp:/tmp/webapi_tmp/

  sipi:
    image: nieine/sipi
    ports:
      - 1024:1024
    volumes:
      - ./tmp:/tmp
      - $HOME:$HOME
      - ./images:/sipi/images
      - ../Knora/webapiTemp:/tmp/webapi_tmp/
      - ../KnoSaSi-PrenuiltImages/sipiConfig:/sipi/config

  salsah:
    build: ./Salsah
    ports:
      - 4200:4200
